create table  user (
  id uuid not null,
  created_at timestamp with time zone not null default now(),
  nome text null,
  profile_img text null,
  constraint user_pkey primary key (id),
  constraint user_id_fkey foreign KEY (id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table  chat (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  chat_name text null,
  chat_description text null,
  chat_img text null,
  chat_members text[] null,
  last_message text null,
  last_message_time time without time zone null,
  constraint chat_pkey primary key (id)
) TABLESPACE pg_default;

create table  mensagens (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  message_text text null,
  sender_id uuid null,
  recipient_id uuid null,
  img_path text null,
  constraint mensagens_pkey primary key (id),
  constraint mensagens_recipient_id_fkey foreign KEY (recipient_id) references chat (id) on update CASCADE on delete CASCADE,
  constraint mensagens_sender_id_fkey foreign KEY (sender_id) references "user" (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;