create table loja_perfil (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nome text null,
  email text null,
  foto_perfil text null,
  sexo text null,
  pais text null,
  estado text null,
  
  user_id uuid null,
  empresa_id bigint null,
  constraint loja_perfil_pkey primary key (id),
  constraint loja_perfil_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table loja_empresa (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nome text null,
  logo text null,
  
  perfil_id bigint null,
  constraint loja_empresa_pkey primary key (id),
  constraint loja_empresa_perfil_id_fkey foreign KEY (perfil_id) references loja_perfil (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table loja_produto (
  id bigint primary key generated always as identity,
  created_at timestamp with time zone not null default now(),
  nome text not null,
  preco numeric(10, 2) not null
  foto_produto text not null,
);

create table loja_pedido (
  id bigint primary key generated always as identity,
  created_at timestamp with time zone not null default now(),
  total numeric(10, 2) not null default 0
);

create table loja_pedido_item (
  id bigint primary key generated always as identity,
  created_at timestamp with time zone not null default now(),
  pedido_id bigint references pedido (id) on delete cascade,
  produto_id bigint references produto (id) on delete cascade,
  
  quantidade integer not null,
  preco_unitario numeric(10, 2) not null,
  total_item numeric(10, 2) not null
);

/*
Objetivo: representar os itens dentro de um pedido.

💡 Campos:
    id: chave primária.
    pedido_id: chave estrangeira → indica a qual pedido o item pertence.
    produto_id: chave estrangeira → qual produto foi comprado.
    quantidade: número de unidades.
    preco_unitario: preço do produto no momento da venda (importante, 
    porque pode ser diferente do preço atual em produto).
    total_item: valor total do item (quantidade × preco_unitario).
💡 Boas práticas aplicadas:
    Guardar o preco_unitario evita inconsistência caso o preço do produto mude depois.
    O total_item também é armazenado para agilizar cálculos (embora pudesse ser calculado "on the fly").
*/
create
or replace function update_pedido_total () returns trigger as $$
BEGIN
    UPDATE loja_pedido
    SET total = (SELECT COALESCE(SUM(total_item), 0) FROM pedido_item WHERE pedido_id = NEW.pedido_id)
    WHERE id = NEW.pedido_id;
    RETURN NEW;
END;
$$ language plpgsql;

    /*
      💡 Objetivo: manter o campo pedido.total sempre atualizado automaticamente.
          Sempre que um item é inserido ou atualizado em pedido_item, o trigger dispara e:
          Soma todos os total_item daquele pedido.
          Atualiza o valor de pedido.total.

      💡 Observações:
          Isso elimina risco de inconsistência entre o que está em pedido e os itens.
          Porém, ainda não cobre o caso de DELETE em pedido_item. Se um item for removido, 
          o total não será atualizado. Nesse caso, seria bom incluir também AFTER DELETE.
    */
create trigger update_pedido_total_trigger
after insert
or
update on loja_pedido_item for each row
execute function update_pedido_total ();

/**    
    📌 Análise geral
    
    ✅ Pontos fortes:
        Estrutura clara e simples, com separação entre entidades (produto, pedido, pedido_item).
        Boa prática em salvar preco_unitario e total_item no momento da venda.
        Trigger garante que o pedido.total esteja sempre atualizado.
        Uso de on delete cascade → remove automaticamente os itens de um pedido apagado (evita lixo no banco).
    
    ⚠️ Possíveis pontos de melhoria:
        Trigger incompleto: não cobre DELETE em pedido_item.
        Solução: adicionar AFTER DELETE no mesmo trigger.
        Duplicação de dados (total_item): já que é quantidade * preco_unitario, pode ser calculado em runtime. Mas manter facilita consultas e 
        relatórios → trade-off entre espaço e performance.
        Campo total em pedido: também é redundante (pois pode ser calculado via SUM(total_item)), mas está ok porque melhora desempenho e 
        simplifica consultas.
        Faltam atributos em pedido: normalmente teríamos cliente, data do pedido, status (em aberto, pago, cancelado etc.).
*/